// src/components/islands/Hobbies.svelte
<script lang="ts">
    interface HobbiesOption {
        text: string;
        active: boolean;
    }

    let hobbyOptions = [
        {
            text: "loving zod",
            active: true,
        },
        {
            text: "exercising with volumn cycles",
            active: false,
        },
        {
            text: "rebuilding my shonen jump api",
            active: true,
        },
        {
            text: "finally playing the Breath of the Wild",
            active: true,
        },
    ].filter((option) => option.active) as HobbiesOption[];

    let index = 0;
    let ms = 5000;
    const setIndex = () =>
        (index = Math.floor(Math.random() * hobbyOptions.length));

    let clear: NodeJS.Timeout;
    $: {
        clearInterval(clear);
        clear = setInterval(setIndex, ms);
    }
</script>

<span class="text-sm lowercase text-orange-400">{hobbyOptions[index].text}</span
>

// src/components/islands/Hobbies.tsx
import { createSignal, onCleanup, onMount } from "solid-js";

interface HobbiesOption {
    text: string;
    active: boolean;
    link: string;
}

const hobbiesOptions = [
    {
        text: "loving zod",
        active: true,
        link: "",
    },
    {
        text: "exercising with volumn cycles",
        active: true,
        link: "",
    },
    {
        text: "rebuilding my shonen jump api",
        active: true,
        link: "",
    },
    {
        text: "playing the stanley parable",
        active: true,
        link: "",
    },
];

const getHobbies = (hobbiesOptions: HobbiesOption[]) => {
    const active = hobbiesOptions.filter((option) => option.active);
    return active[Math.floor(Math.random() * hobbiesOptions.length)].text;
};

export function Hobbies() {
    const [subhobby, setHobby] = createSignal("");
    onMount(() => {
        const firstHobby = getHobbies(hobbiesOptions);
        setHobby(firstHobby);
    });

    const timer = setInterval(() => {
        const newHobby = getHobbies(hobbiesOptions);
        setHobby(newHobby);
    }, 5000);
    onCleanup(() => clearInterval(timer));

    return <span class="text-sm lowercase text-orange-400">{subhobby()}</span>;
}
